# Generated by Django 2.1.5 on 2019-02-06 16:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('convertor', '0003_auto_20190205_2206'),
    ]

    operations = [
        migrations.AddField(
            model_name='currencies',
            name='units',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
